<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup Label="Source">
		<PackageVersion Include="Microsoft.AspNetCore.DataProtection" Version="10.0.10" />
		<PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.10" />
		<PackageVersion Include="Dapper" Version="2.1.79" />
		<PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.2" />
		<PackageVersion Include="Npgsql" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup Label="Tests">
		<PackageVersion Include="Bogus" Version="35.6.5" />
		<PackageVersion Include="NSubstitute" Version="6.0.0" />
		<PackageVersion Include="FluentAssertions" Version="8.10.0" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageVersion Include="xunit.v3" Version="3.2.2" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
		<PackageVersion Include="Respawn" Version="7.0.0" />
		<PackageVersion Include="Testcontainers.PostgreSql" Version="4.13.0" />
		<PackageVersion Include="Testcontainers.MsSql" Version="4.13.0" />
	</ItemGroup>
</Project>
