<Project Sdk="Microsoft.NET.Sdk">



	<ItemGroup>
	  <ProjectReference Include="..\..\src\AspNetCore.DataProtection.CustomStorage\AspNetCore.DataProtection.CustomStorage.csproj" />
	  <ProjectReference Include="..\..\src\AspNetCore.DataProtection.CustomStorage.Dapper\AspNetCore.DataProtection.CustomStorage.Dapper.csproj" />
	  <ProjectReference Include="..\..\src\AspNetCore.DataProtection.CustomStorage.Dapper.SQLServer\AspNetCore.DataProtection.CustomStorage.Dapper.SQLServer.csproj" />
	  <ProjectReference Include="..\..\src\AspNetCore.DataProtection.CustomStorage.Dapper.PostgreSQL\AspNetCore.DataProtection.CustomStorage.Dapper.PostgreSQL.csproj" />


	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Respawn" />
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="Testcontainers.MsSql" />
	</ItemGroup>


</Project>
